<?xml version="1.0"?>

<!DOCTYPE note1 [
<!ELEMENT note1 (to,from,location,heading,body)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT body (#PCDATA)>
]>
<note1>
<to>Pradeep</to>
<from>Vivek</from>
<location>bangalore</location>
<heading>Reminder</heading>
<body>Will be attending the class today</body>
</note1>